import { BLUEPRINT_AXES } from "../types/axis";
import type { HumanVocabulary } from "../types/runtime";

type HumanVocabularyDraft = Omit<HumanVocabulary, "category">;

function categoryForId(id: string) {
  const numericId = Number(id.replace("ID", ""));

  if (numericId <= 20) return "A. 자기 기준과 정체 구조";
  if (numericId <= 40) return "B. 사고와 정보 처리";
  if (numericId <= 60) return "C. 결정과 선택 방식";
  if (numericId <= 80) return "D. 실행과 반복 구조";
  if (numericId <= 100) return "E. 관계와 거리 조절";
  if (numericId <= 120) return "F. 표현과 전달 방식";
  if (numericId <= 140) return "G. 영향력과 책임 구조";
  if (numericId <= 160) return "H. 갈등과 경계 구조";
  if (numericId <= 180) return "I. 자원과 일의 구조";
  return "J. 회복과 흐름 구조";
}

function assertVocabularyRegistry(vocabulary: HumanVocabulary[]) {
  const axisSet = new Set(BLUEPRINT_AXES);
  const seenIds = new Set<string>();

  vocabulary.forEach((item) => {
    if (seenIds.has(item.id)) {
      throw new Error(`Duplicate Human Vocabulary id: ${item.id}`);
    }

    seenIds.add(item.id);

    item.relatedAxes.forEach((axis) => {
      if (!axisSet.has(axis)) {
        throw new Error(`Invalid axis ${axis} in Human Vocabulary ${item.id}`);
      }
    });
  });
}

const HUMAN_VOCABULARY_DRAFTS: HumanVocabularyDraft[] = [
  {
    id: "ID001",
    name: "기준을 먼저 만든다",
    description: "빠른 결정보다 판단 기준을 먼저 세운 뒤 움직인다.",
    opposite: "상황에 맞춰 즉시 움직인다.",
    relatedAxes: ["Identity", "Decision", "Thinking"],
    featureSource: ["FEATURE_DECISION_CRITERIA", "FEATURE_IDENTITY_SELF_STANDARD"],
    confidenceRule: "결정 기준 feature와 자기 기준 feature가 함께 Stable 이상일 때 중심 Vocabulary로 사용한다.",
    writerHints: ["결정이 느린 사람이 아니라 기준을 먼저 만드는 사람으로 쓴다."],
    readerHints: ["Decision Annotation의 대표 구조로 사용한다."],
  },
  {
    id: "ID021",
    name: "큰 그림을 먼저 본다",
    description: "세부를 보기 전 전체 구조와 방향을 먼저 잡는다.",
    opposite: "세부에서 전체로 올라간다.",
    relatedAxes: ["Thinking", "Decision"],
    featureSource: ["FEATURE_THINKING_BIG_PICTURE", "FEATURE_THINKING_STRUCTURE_FIRST"],
    confidenceRule: "사고 구조 feature가 Thinking 축에서 반복될 때 사용한다.",
    writerHints: ["대충 보는 사람이 아니라 먼저 지도를 그리는 사람으로 쓴다."],
    readerHints: ["Thinking Annotation의 보조 구조로 사용한다."],
  },
  {
    id: "ID024",
    name: "질문으로 생각한다",
    description: "답을 바로 내기보다 질문을 바꾸며 생각을 전개한다.",
    opposite: "답을 먼저 확정한다.",
    relatedAxes: ["Thinking", "Communication"],
    featureSource: ["FEATURE_THINKING_QUESTION_DRIVEN", "FEATURE_COMMUNICATION_QUESTION_PERSUASION"],
    confidenceRule: "질문 기반 사고와 질문 설득이 함께 잡힐 때 사용한다.",
    writerHints: ["답을 미루는 것이 아니라 질문을 바꾸는 힘으로 쓴다."],
    readerHints: ["사고와 소통이 함께 보이는 문장에 붙인다."],
  },
  {
    id: "ID028",
    name: "패턴을 빠르게 찾는다",
    description: "반복되는 흐름과 구조를 빠르게 감지한다.",
    opposite: "매번 새 사건으로 본다.",
    relatedAxes: ["Thinking", "LifeFlow"],
    featureSource: ["FEATURE_THINKING_PATTERN_SEEKING", "FEATURE_LIFEFLOW_REPEATING_TASK"],
    confidenceRule: "패턴 탐색과 반복 과제 feature가 함께 있을 때 사용한다.",
    writerHints: ["사건보다 반복 구조를 읽는 사람으로 쓴다."],
    readerHints: ["LifeFlow 근거와 함께 Appendix로 연결한다."],
  },
  {
    id: "ID041",
    name: "검증 후 움직인다",
    description: "가능성이 보여도 검증이 끝나야 실제 행동으로 옮긴다.",
    opposite: "가능성이 보이면 바로 움직인다.",
    relatedAxes: ["Decision", "Action"],
    featureSource: ["FEATURE_DECISION_VERIFICATION", "FEATURE_THINKING_EVIDENCE_CHECK"],
    confidenceRule: "검증 feature가 High 또는 Stable이고 실행 feature가 보조할 때 사용한다.",
    writerHints: ["회피가 아니라 검증 후 이동으로 쓴다."],
    readerHints: ["ID001의 supporting Vocabulary로 자주 사용한다."],
  },
  {
    id: "ID049",
    name: "결정을 미루며 정보를 모은다",
    description: "미룸이 회피가 아니라 판단 재료를 채우는 과정일 때가 많다.",
    opposite: "정보가 부족해도 결정한다.",
    relatedAxes: ["Decision", "Thinking"],
    featureSource: ["FEATURE_THINKING_LAYERED_MEMORY", "FEATURE_DECISION_VERIFICATION"],
    confidenceRule: "정보 축적과 검증 후 이동이 함께 잡힐 때 사용한다.",
    writerHints: ["미룸을 결핍으로 쓰지 않는다."],
    readerHints: ["조건부 confidence가 붙는 문장에 사용한다."],
  },
  {
    id: "ID050",
    name: "선택 후 오래 버틴다",
    description: "한 번 선택하면 쉽게 갈아타지 않고 충분히 밀어본다.",
    opposite: "선택 후 자주 바꾼다.",
    relatedAxes: ["Decision", "Action"],
    featureSource: ["FEATURE_ACTION_SUSTAINED_RHYTHM", "FEATURE_DECISION_LONG_TERM_VIEW"],
    confidenceRule: "지속 리듬과 장기 관점이 함께 Stable 이상일 때 사용한다.",
    writerHints: ["납득한 일에는 오래 버티는 힘으로 쓴다."],
    readerHints: ["Action과 Decision을 잇는 Annotation에 사용한다."],
  },
  {
    id: "ID060",
    name: "기회보다 준비 상태를 본다",
    description: "좋은 기회라도 자신이 감당할 준비가 되었는지 먼저 확인한다.",
    opposite: "기회가 오면 먼저 잡는다.",
    relatedAxes: ["Decision", "LifeFlow"],
    featureSource: ["FEATURE_DECISION_RESOURCE_CHECK", "FEATURE_LIFEFLOW_PREPARATION_FOR_NEXT"],
    confidenceRule: "자원 점검과 다음 장 준비 feature가 함께 있을 때 사용한다.",
    writerHints: ["기회 회피가 아니라 준비 상태 확인으로 쓴다."],
    readerHints: ["현재 흐름 문장에 붙인다."],
  },
  {
    id: "ID061",
    name: "실행으로 증명한다",
    description: "말이나 계획보다 실제 결과로 자신의 생각을 확인한다.",
    opposite: "설명으로 먼저 증명한다.",
    relatedAxes: ["Action", "Communication"],
    featureSource: ["FEATURE_ACTION_EXECUTION_DRIVEN", "FEATURE_COMMUNICATION_ACTION_CHANNEL"],
    confidenceRule: "실행 증명과 행동 채널이 함께 잡힐 때 사용한다.",
    writerHints: ["말보다 행동으로 확인하는 구조로 쓴다."],
    readerHints: ["Action Annotation에 사용한다."],
  },
  {
    id: "ID062",
    name: "시작보다 지속이 강하다",
    description: "처음 속도는 빠르지 않아도 시작한 일을 오래 끌고 간다.",
    opposite: "시작은 빠르지만 쉽게 식는다.",
    relatedAxes: ["Action", "Growth"],
    featureSource: ["FEATURE_ACTION_SLOW_IGNITION", "FEATURE_ACTION_SUSTAINED_RHYTHM"],
    confidenceRule: "늦게 붙는 실행과 지속 리듬이 함께 잡힐 때 사용한다.",
    writerHints: ["불꽃보다 불씨의 리듬으로 쓴다."],
    readerHints: ["Action 핵심 구조로 사용한다."],
  },
  {
    id: "ID079",
    name: "멈춤을 실행의 일부로 둔다",
    description: "쉬는 시간을 낭비가 아니라 다음 실행을 위한 조정으로 본다.",
    opposite: "멈춤을 실패로 본다.",
    relatedAxes: ["Action", "Health"],
    featureSource: ["FEATURE_HEALTH_STOP_AS_RECOVERY", "FEATURE_HEALTH_RHYTHM_RECOVERY"],
    confidenceRule: "회복과 실행 리듬 feature가 함께 있을 때 사용한다.",
    writerHints: ["멈춤을 실패가 아니라 조정으로 쓴다."],
    readerHints: ["Health와 Action을 잇는 문장에 붙인다."],
  },
  {
    id: "ID081",
    name: "사람을 오래 관찰한다",
    description: "가까워지기 전에 말, 행동, 반복을 충분히 본다.",
    opposite: "첫 느낌으로 가까워진다.",
    relatedAxes: ["Relationship", "Thinking"],
    featureSource: ["FEATURE_RELATIONSHIP_OBSERVATION", "FEATURE_THINKING_CONTEXT_READING"],
    confidenceRule: "관계 관찰과 맥락 읽기가 함께 잡힐 때 사용한다.",
    writerHints: ["차가움보다 오래 관찰하는 방식으로 쓴다."],
    readerHints: ["Relationship Annotation에 사용한다."],
  },
  {
    id: "ID082",
    name: "신뢰를 천천히 연다",
    description: "처음부터 전부 보여주지 않고 시간을 거쳐 신뢰를 만든다.",
    opposite: "신뢰를 빠르게 연다.",
    relatedAxes: ["Relationship", "Identity"],
    featureSource: ["FEATURE_RELATIONSHIP_TRUST_BEFORE_SPEED", "FEATURE_IDENTITY_BOUNDARY_FIRST"],
    confidenceRule: "속도보다 신뢰 feature와 경계 우선 feature가 함께 있을 때 사용한다.",
    writerHints: ["마음을 둘 자리를 확인하는 사람으로 쓴다."],
    readerHints: ["관계 핵심 구조로 사용한다."],
  },
  {
    id: "ID093",
    name: "관계의 시작보다 유지에 강하다",
    description: "처음 다가가는 것보다 오래 유지하고 챙기는 데 강점이 있다.",
    opposite: "시작은 쉽지만 유지가 어렵다.",
    relatedAxes: ["Relationship", "Growth"],
    featureSource: ["FEATURE_RELATIONSHIP_LONG_TERM_MAINTENANCE", "FEATURE_GROWTH_ACCUMULATION"],
    confidenceRule: "장기 유지와 누적 성장 feature가 함께 있을 때 사용한다.",
    writerHints: ["오래 닫히지 않는 관계의 방으로 쓴다."],
    readerHints: ["관계 후반 문장에 붙인다."],
  },
  {
    id: "ID101",
    name: "짧게 핵심을 말한다",
    description: "긴 설명보다 핵심 문장으로 방향을 잡아준다.",
    opposite: "충분히 길게 풀어 설명한다.",
    relatedAxes: ["Communication", "Leadership"],
    featureSource: ["FEATURE_COMMUNICATION_WORD_RESPONSIBILITY", "FEATURE_LEADERSHIP_STANDARD_BASED"],
    confidenceRule: "말의 책임과 기준 기반 영향이 함께 잡힐 때 사용한다.",
    writerHints: ["말의 양보다 책임의 밀도로 쓴다."],
    readerHints: ["소통 문장에 붙인다."],
  },
  {
    id: "ID108",
    name: "침묵으로 정리한다",
    description: "말이 없을 때도 관계를 끊은 것이 아니라 내부 정리 중일 수 있다.",
    opposite: "말로 바로 푼다.",
    relatedAxes: ["Communication", "Health"],
    featureSource: ["FEATURE_COMMUNICATION_LATE_CLEAR_VOICE", "FEATURE_HEALTH_QUIET_RECOVERY"],
    confidenceRule: "늦지만 분명한 말과 조용한 회복이 함께 있을 때 사용한다.",
    writerHints: ["침묵을 결핍으로 쓰지 않는다."],
    readerHints: ["Reader 각주에서는 짧게 유지한다."],
  },
  {
    id: "ID121",
    name: "기준으로 사람을 움직인다",
    description: "감정 호소보다 지켜야 할 기준을 제시해 방향을 만든다.",
    opposite: "분위기로 사람을 움직인다.",
    relatedAxes: ["Leadership", "Decision"],
    featureSource: ["FEATURE_LEADERSHIP_STANDARD_BASED", "FEATURE_DECISION_CRITERIA"],
    confidenceRule: "기준 기반 영향과 결정 기준이 함께 High 또는 Stable일 때 사용한다.",
    writerHints: ["화려한 리더십 표현을 피하고 기준점으로 쓴다."],
    readerHints: ["Leadership Annotation에 사용한다."],
  },
  {
    id: "ID127",
    name: "사람보다 시스템을 본다",
    description: "특정 개인보다 일이 반복 가능하게 돌아가는 구조를 만든다.",
    opposite: "시스템보다 사람의 의지를 본다.",
    relatedAxes: ["Leadership", "Thinking"],
    featureSource: ["FEATURE_LEADERSHIP_SYSTEM_THINKING", "FEATURE_THINKING_STRUCTURE_FIRST"],
    confidenceRule: "시스템 사고와 구조 우선 feature가 함께 있을 때 사용한다.",
    writerHints: ["사람을 낮게 보는 표현으로 쓰지 않는다."],
    readerHints: ["일과 역할 문장에 붙인다."],
  },
  {
    id: "ID141",
    name: "갈등을 늦게 드러낸다",
    description: "불편함을 바로 표현하지 않고 내부에서 오래 검토한다.",
    opposite: "불편함을 바로 드러낸다.",
    relatedAxes: ["Conflict", "Communication"],
    featureSource: ["FEATURE_CONFLICT_BOUNDARY_AFTER_PATIENCE", "FEATURE_COMMUNICATION_LATE_CLEAR_VOICE"],
    confidenceRule: "참은 뒤의 경계와 늦지만 분명한 말이 함께 있을 때 사용한다.",
    writerHints: ["참음이 길어지는 위험도 함께 쓴다."],
    readerHints: ["Risk 구조에 붙인다."],
  },
  {
    id: "ID143",
    name: "갈등을 구조 문제로 본다",
    description: "개인 감정보다 반복되는 조건과 구조를 먼저 본다.",
    opposite: "개인 감정으로 갈등을 본다.",
    relatedAxes: ["Conflict", "Thinking"],
    featureSource: ["FEATURE_CONFLICT_STRUCTURE_DIAGNOSIS", "FEATURE_THINKING_STRUCTURE_FIRST"],
    confidenceRule: "갈등 구조 진단과 구조 우선 feature가 함께 있을 때 사용한다.",
    writerHints: ["감정을 지우지 말고 구조를 먼저 본다고 쓴다."],
    readerHints: ["Conflict Annotation에 사용한다."],
  },
  {
    id: "ID161",
    name: "가치를 자원으로 바꾼다",
    description: "가진 능력이나 경험을 실제 쓸 수 있는 자원으로 전환한다.",
    opposite: "가치를 안에만 보관한다.",
    relatedAxes: ["Wealth", "Action"],
    featureSource: ["FEATURE_WEALTH_VALUE_CONVERSION", "FEATURE_ACTION_COMPLETION_STACKING"],
    confidenceRule: "가치 전환과 작은 완료 누적이 함께 있을 때 사용한다.",
    writerHints: ["돈보다 자원화 능력으로 쓴다."],
    readerHints: ["Wealth Annotation에 사용한다."],
  },
  {
    id: "ID167",
    name: "안정성이 있어야 확장한다",
    description: "기본 자원이 확보되어야 더 큰 시도를 시작한다.",
    opposite: "확장하면서 안정성을 만든다.",
    relatedAxes: ["Wealth", "Decision"],
    featureSource: ["FEATURE_WEALTH_STABILITY_BEFORE_EXPANSION", "FEATURE_DECISION_RESOURCE_CHECK"],
    confidenceRule: "안정 후 확장과 자원 점검 feature가 함께 있을 때 사용한다.",
    writerHints: ["확장을 막는 것이 아니라 기반을 먼저 보는 구조로 쓴다."],
    readerHints: ["현재 준비 문장에 붙인다."],
  },
  {
    id: "ID181",
    name: "조용히 회복한다",
    description: "자극을 늘리기보다 외부 입력을 줄일 때 회복된다.",
    opposite: "사람과 자극 속에서 회복한다.",
    relatedAxes: ["Health", "Relationship"],
    featureSource: ["FEATURE_HEALTH_QUIET_RECOVERY", "FEATURE_RELATIONSHIP_DISTANCE_CONTROL"],
    confidenceRule: "조용한 회복과 거리 조절 feature가 함께 있을 때 사용한다.",
    writerHints: ["혼자 있음이 관계를 지키는 시간으로 쓴다."],
    readerHints: ["Health Annotation에 사용한다."],
  },
  {
    id: "ID189",
    name: "현재 흐름을 읽고 움직인다",
    description: "지금이 확장할 때인지 정리할 때인지 확인하고 행동을 맞춘다.",
    opposite: "흐름과 무관하게 목표를 밀어붙인다.",
    relatedAxes: ["LifeFlow", "Decision"],
    featureSource: ["FEATURE_LIFEFLOW_REALIGNMENT", "FEATURE_LIFEFLOW_TIMING_MODIFIER"],
    confidenceRule: "재정렬 흐름과 흐름 보정 feature가 함께 있을 때 사용한다.",
    writerHints: ["예언하지 말고 현재 흐름의 읽기로 쓴다."],
    readerHints: ["LifeFlow 핵심 구조에 사용한다."],
  },
  {
    id: "ID200",
    name: "다음 장을 준비한다",
    description: "현재 결론보다 다음 시기에 필요한 자원과 태도를 준비한다.",
    opposite: "지금의 결론에 머문다.",
    relatedAxes: ["LifeFlow", "Growth"],
    featureSource: ["FEATURE_LIFEFLOW_PREPARATION_FOR_NEXT", "FEATURE_GROWTH_SELF_REVISION"],
    confidenceRule: "다음 장 준비와 자기 수정 feature가 함께 있을 때 사용한다.",
    writerHints: ["미래 예언이 아니라 다음 장의 준비로 쓴다."],
    readerHints: ["마지막 챕터와 Writer Input 결론에 사용한다."],
  },
  {
    id: "ID002",
    name: "자기 언어로 설명한다",
    description: "남의 표현을 그대로 빌리기보다 자신의 말로 납득될 때 받아들인다.",
    opposite: "주어진 설명을 그대로 따른다.",
    relatedAxes: ["Identity", "Communication"],
    featureSource: ["FEATURE_IDENTITY_INNER_ALIGNMENT", "FEATURE_COMMUNICATION_WORD_RESPONSIBILITY"],
    confidenceRule: "내부 정렬과 말의 책임 feature가 함께 있을 때 사용한다.",
    writerHints: ["자기 언어로 납득하는 구조로 쓴다."],
    readerHints: ["Identity와 Communication 사이에 붙인다."],
  },
  {
    id: "ID010",
    name: "오래 남는 방향을 고른다",
    description: "당장의 편함보다 시간이 지나도 유지될 선택을 선호한다.",
    opposite: "즉시 편한 방향을 고른다.",
    relatedAxes: ["Identity", "Decision", "LifeFlow"],
    featureSource: ["FEATURE_IDENTITY_LONG_TERM_SELF", "FEATURE_DECISION_LONG_TERM_VIEW"],
    confidenceRule: "장기 자기감과 장기 관점이 함께 있을 때 사용한다.",
    writerHints: ["오래 남는 방향이라는 표현으로 쓴다."],
    readerHints: ["장기 방향 문장에 붙인다."],
  },
  {
    id: "ID015",
    name: "중심이 흔들리면 멈춘다",
    description: "바쁘게 밀고 가기보다 자신이 왜 하는지 흐려질 때 멈춘다.",
    opposite: "흔들려도 속도를 유지한다.",
    relatedAxes: ["Identity", "Health"],
    featureSource: ["FEATURE_IDENTITY_INNER_ALIGNMENT", "FEATURE_HEALTH_STOP_AS_RECOVERY"],
    confidenceRule: "내부 정렬과 멈춤 회복 feature가 함께 있을 때 사용한다.",
    writerHints: ["멈춤을 실패가 아니라 중심 회복으로 쓴다."],
    readerHints: ["Risk와 Health에 붙인다."],
  },
  {
    id: "ID022",
    name: "디테일을 놓치지 않는다",
    description: "작은 차이와 예외를 빠르게 감지하고 판단에 반영한다.",
    opposite: "큰 방향만 보고 넘어간다.",
    relatedAxes: ["Thinking", "Action"],
    featureSource: ["FEATURE_THINKING_DETAIL_SENSITIVE", "FEATURE_THINKING_EVIDENCE_CHECK"],
    confidenceRule: "디테일 감지와 근거 확인 feature가 함께 있을 때 사용한다.",
    writerHints: ["예민함보다 차이 감지로 쓴다."],
    readerHints: ["검증 Annotation에 붙인다."],
  },
  {
    id: "ID023",
    name: "감정보다 원리를 찾는다",
    description: "감정 반응 뒤에 어떤 원리와 구조가 있는지 보려 한다.",
    opposite: "감정 반응을 우선 따른다.",
    relatedAxes: ["Thinking", "Conflict"],
    featureSource: ["FEATURE_THINKING_STRUCTURE_FIRST", "FEATURE_CONFLICT_STRUCTURE_DIAGNOSIS"],
    confidenceRule: "구조 우선과 갈등 구조 진단이 함께 있을 때 사용한다.",
    writerHints: ["감정을 지우지 말고 원리를 함께 본다고 쓴다."],
    readerHints: ["Conflict와 Thinking에 붙인다."],
  },
  {
    id: "ID029",
    name: "문제를 다시 정의한다",
    description: "주어진 문제를 그대로 풀기보다 질문 자체를 바꾼다.",
    opposite: "주어진 문제 안에서 답을 찾는다.",
    relatedAxes: ["Thinking", "Growth"],
    featureSource: ["FEATURE_THINKING_STRUCTURE_FIRST", "FEATURE_GROWTH_SELF_REVISION"],
    confidenceRule: "구조 우선과 자기 수정 feature가 함께 있을 때 사용한다.",
    writerHints: ["문제를 바꿔 보는 힘으로 쓴다."],
    readerHints: ["성장 이유에 붙인다."],
  },
  {
    id: "ID034",
    name: "경험을 개념으로 바꾼다",
    description: "겪은 일을 그냥 넘기지 않고 설명 가능한 구조로 정리한다.",
    opposite: "경험을 경험으로만 둔다.",
    relatedAxes: ["Thinking", "Growth"],
    featureSource: ["FEATURE_THINKING_LAYERED_MEMORY", "FEATURE_GROWTH_FAILURE_TO_RULE"],
    confidenceRule: "층으로 쌓는 기억과 실패를 기준으로 전환하는 feature가 함께 있을 때 사용한다.",
    writerHints: ["경험을 기준으로 저장한다고 쓴다."],
    readerHints: ["Growth Annotation에 붙인다."],
  },
  {
    id: "ID042",
    name: "선택지를 좁힌 뒤 결정한다",
    description: "넓게 펼친 뒤 기준에 맞지 않는 선택지를 제거한다.",
    opposite: "처음 보이는 선택지로 결정한다.",
    relatedAxes: ["Decision", "Thinking"],
    featureSource: ["FEATURE_DECISION_CRITERIA", "FEATURE_THINKING_BIG_PICTURE"],
    confidenceRule: "결정 기준과 큰 그림 feature가 함께 있을 때 사용한다.",
    writerHints: ["선택지를 기준으로 좁히는 구조로 쓴다."],
    readerHints: ["Decision Annotation에 붙인다."],
  },
  {
    id: "ID044",
    name: "조건이 맞으면 빠르게 결정한다",
    description: "평소에는 신중하지만 필요한 조건이 모이면 속도가 빨라진다.",
    opposite: "조건과 무관하게 느리게 결정한다.",
    relatedAxes: ["Decision", "Action"],
    featureSource: ["FEATURE_DECISION_CONDITION_TRIGGERED_SPEED", "FEATURE_ACTION_DEADLINE_ACTIVATION"],
    confidenceRule: "조건형 속도와 마감 활성 feature가 함께 있을 때 사용한다.",
    writerHints: ["항상 느린 사람이 아니라 조건형 속도라고 쓴다."],
    readerHints: ["Tension 구조에 붙인다."],
  },
  {
    id: "ID052",
    name: "결정 전에 자원 영향을 본다",
    description: "시간, 돈, 체력, 기회비용을 함께 계산한다.",
    opposite: "끌리는 방향을 먼저 택한다.",
    relatedAxes: ["Decision", "Wealth"],
    featureSource: ["FEATURE_DECISION_RESOURCE_CHECK", "FEATURE_WEALTH_TIME_COST_AWARENESS"],
    confidenceRule: "자원 점검과 시간 비용 감각이 함께 있을 때 사용한다.",
    writerHints: ["선택 비용을 넓게 본다고 쓴다."],
    readerHints: ["WriterInput weak signal에도 쓸 수 있다."],
  },
  {
    id: "ID065",
    name: "반복으로 숙련된다",
    description: "같은 과정을 여러 번 거치며 정확도와 속도가 올라간다.",
    opposite: "새 자극이 있어야 숙련된다.",
    relatedAxes: ["Action", "Growth"],
    featureSource: ["FEATURE_ACTION_ROUTINE_POWER", "FEATURE_ACTION_SUSTAINED_RHYTHM"],
    confidenceRule: "루틴 힘과 지속 리듬 feature가 함께 있을 때 사용한다.",
    writerHints: ["반복을 안정된 숙련으로 쓴다."],
    readerHints: ["Action에 붙인다."],
  },
  {
    id: "ID066",
    name: "마감이 오면 살아난다",
    description: "제한 시간이 분명해지면 집중력과 실행 속도가 올라간다.",
    opposite: "마감이 오면 무너진다.",
    relatedAxes: ["Action", "Conflict"],
    featureSource: ["FEATURE_ACTION_DEADLINE_ACTIVATION", "FEATURE_LEADERSHIP_CRISIS_ROLE"],
    confidenceRule: "마감 활성과 위기 역할 feature가 함께 있을 때 사용한다.",
    writerHints: ["압박 아래 선명해지는 실행으로 쓴다."],
    readerHints: ["조건부 실행에 붙인다."],
  },
  {
    id: "ID072",
    name: "작은 완료를 쌓는다",
    description: "큰 목표보다 작은 완료 단위를 쌓아 추진력을 만든다.",
    opposite: "큰 목표 하나로 밀어붙인다.",
    relatedAxes: ["Action", "Wealth"],
    featureSource: ["FEATURE_ACTION_COMPLETION_STACKING", "FEATURE_WEALTH_VALUE_CONVERSION"],
    confidenceRule: "작은 완료 누적과 가치 전환 feature가 함께 있을 때 사용한다.",
    writerHints: ["작은 완료가 다음 실행을 만든다고 쓴다."],
    readerHints: ["Action과 Wealth에 붙인다."],
  },
  {
    id: "ID084",
    name: "필요한 거리를 둔다",
    description: "좋아하는 사람과도 자신이 유지될 거리를 확보한다.",
    opposite: "가까우면 거리를 줄인다.",
    relatedAxes: ["Relationship", "Health"],
    featureSource: ["FEATURE_RELATIONSHIP_DISTANCE_CONTROL", "FEATURE_HEALTH_QUIET_RECOVERY"],
    confidenceRule: "거리 조절과 조용한 회복 feature가 함께 있을 때 사용한다.",
    writerHints: ["거리를 관계 유지 조건으로 쓴다."],
    readerHints: ["Relationship Annotation에 붙인다."],
  },
  {
    id: "ID085",
    name: "연결을 만든다",
    description: "사람과 사람, 정보와 사람 사이의 연결점을 잘 만든다.",
    opposite: "각자를 따로 둔다.",
    relatedAxes: ["Relationship", "Communication"],
    featureSource: ["FEATURE_RELATIONSHIP_CONNECTION_BUILDING", "FEATURE_COMMUNICATION_QUESTION_PERSUASION"],
    confidenceRule: "연결 만들기와 질문 설득 feature가 함께 있을 때 사용한다.",
    writerHints: ["연결점을 찾는 사람으로 쓴다."],
    readerHints: ["확장 흐름에 붙인다."],
  },
  {
    id: "ID100",
    name: "혼자 있는 시간이 관계를 지킨다",
    description: "혼자 정리하는 시간이 있어야 관계에서도 안정적으로 머문다.",
    opposite: "함께 있는 시간이 관계를 지킨다.",
    relatedAxes: ["Relationship", "Health"],
    featureSource: ["FEATURE_HEALTH_QUIET_RECOVERY", "FEATURE_RELATIONSHIP_DISTANCE_CONTROL"],
    confidenceRule: "조용한 회복과 거리 조절이 함께 있을 때 사용한다.",
    writerHints: ["혼자 있음이 관계를 지키는 시간으로 쓴다."],
    readerHints: ["Health와 Relationship에 붙인다."],
  },
  {
    id: "ID105",
    name: "글로 정리할 때 선명해진다",
    description: "말보다 글에서 기준과 구조가 더 정확하게 나온다.",
    opposite: "말로 할 때 선명해진다.",
    relatedAxes: ["Communication", "Thinking"],
    featureSource: ["FEATURE_COMMUNICATION_WRITTEN_CLARITY", "FEATURE_THINKING_STRUCTURE_FIRST"],
    confidenceRule: "글의 선명함과 구조 우선 feature가 함께 있을 때 사용한다.",
    writerHints: ["글에서 선명해지는 기준으로 쓴다."],
    readerHints: ["저자 노트와 연결한다."],
  },
  {
    id: "ID109",
    name: "질문으로 설득한다",
    description: "주장보다 질문을 통해 상대가 스스로 보게 한다.",
    opposite: "주장으로 설득한다.",
    relatedAxes: ["Communication", "Leadership"],
    featureSource: ["FEATURE_COMMUNICATION_QUESTION_PERSUASION", "FEATURE_LEADERSHIP_QUIET_INFLUENCE"],
    confidenceRule: "질문 설득과 조용한 영향력 feature가 함께 있을 때 사용한다.",
    writerHints: ["질문으로 방향을 열어준다고 쓴다."],
    readerHints: ["Communication에 붙인다."],
  },
  {
    id: "ID120",
    name: "말의 책임을 무겁게 본다",
    description: "한 번 말한 것이 관계와 선택에 영향을 준다고 느낀다.",
    opposite: "말은 상황에 따라 가볍게 바뀐다.",
    relatedAxes: ["Communication", "Identity"],
    featureSource: ["FEATURE_COMMUNICATION_WORD_RESPONSIBILITY", "FEATURE_IDENTITY_SELF_STANDARD"],
    confidenceRule: "말의 책임과 자기 기준 feature가 함께 있을 때 사용한다.",
    writerHints: ["말이 적은 이유를 책임의 무게로 쓴다."],
    readerHints: ["Communication 핵심 구조에 붙인다."],
  },
  {
    id: "ID123",
    name: "뒤에서 판을 정리한다",
    description: "앞에 서기보다 구조와 흐름을 정리해 일이 굴러가게 한다.",
    opposite: "앞에서 방향을 외친다.",
    relatedAxes: ["Leadership", "Thinking"],
    featureSource: ["FEATURE_LEADERSHIP_SYSTEM_THINKING", "FEATURE_THINKING_STRUCTURE_FIRST"],
    confidenceRule: "시스템 사고와 구조 우선 feature가 함께 있을 때 사용한다.",
    writerHints: ["뒤에서 구조를 정리하는 영향력으로 쓴다."],
    readerHints: ["Leadership에 붙인다."],
  },
  {
    id: "ID126",
    name: "위기에서 역할이 선명해진다",
    description: "평소보다 문제가 생겼을 때 자신이 해야 할 일이 분명해진다.",
    opposite: "위기에서 역할이 흐려진다.",
    relatedAxes: ["Leadership", "Conflict"],
    featureSource: ["FEATURE_LEADERSHIP_CRISIS_ROLE", "FEATURE_CONFLICT_DIRECT_CHECK"],
    confidenceRule: "위기 역할과 직접 확인 feature가 함께 있을 때 사용한다.",
    writerHints: ["위기에서 역할이 선명해진다고 쓴다."],
    readerHints: ["Conflict와 Leadership에 붙인다."],
  },
  {
    id: "ID132",
    name: "역할을 나눠 맡긴다",
    description: "혼자 해결하기보다 각자가 잘할 수 있는 몫을 배치한다.",
    opposite: "중요한 일은 직접 처리한다.",
    relatedAxes: ["Leadership", "Wealth"],
    featureSource: ["FEATURE_LEADERSHIP_DELEGATION_STRUCTURE", "FEATURE_WEALTH_SYSTEM_ASSET"],
    confidenceRule: "역할 배치와 시스템 자산화 feature가 함께 있을 때 사용한다.",
    writerHints: ["역할 배치의 구조로 쓴다."],
    readerHints: ["Leadership에 붙인다."],
  },
  {
    id: "ID145",
    name: "정면으로 확인한다",
    description: "애매한 긴장보다 직접 확인하는 편을 택한다.",
    opposite: "시간이 지나길 기다린다.",
    relatedAxes: ["Conflict", "Communication"],
    featureSource: ["FEATURE_CONFLICT_DIRECT_CHECK", "FEATURE_COMMUNICATION_WORD_RESPONSIBILITY"],
    confidenceRule: "직접 확인과 말의 책임 feature가 함께 있을 때 사용한다.",
    writerHints: ["필요할 때 직접 확인한다고 쓴다."],
    readerHints: ["Conflict에 붙인다."],
  },
  {
    id: "ID155",
    name: "화해에도 조건이 필요하다",
    description: "시간이 지났다고 풀리는 것이 아니라 바뀐 조건이 있어야 한다.",
    opposite: "시간이 지나면 자연히 풀린다.",
    relatedAxes: ["Conflict", "Relationship"],
    featureSource: ["FEATURE_CONFLICT_REPAIR_CONDITIONS", "FEATURE_RELATIONSHIP_TRUST_BEFORE_SPEED"],
    confidenceRule: "회복 조건과 속도보다 신뢰 feature가 함께 있을 때 사용한다.",
    writerHints: ["화해를 조건 변화로 쓴다."],
    readerHints: ["Relationship risk에 붙인다."],
  },
  {
    id: "ID160",
    name: "갈등에서 배운 기준을 저장한다",
    description: "한 번 겪은 충돌을 다음 관계와 선택의 기준으로 바꾼다.",
    opposite: "갈등을 지나간 사건으로 둔다.",
    relatedAxes: ["Conflict", "Growth"],
    featureSource: ["FEATURE_CONFLICT_STRUCTURE_DIAGNOSIS", "FEATURE_GROWTH_FAILURE_TO_RULE"],
    confidenceRule: "갈등 구조 진단과 실패를 기준으로 전환하는 feature가 함께 있을 때 사용한다.",
    writerHints: ["갈등을 기준으로 저장한다고 쓴다."],
    readerHints: ["Growth와 Conflict에 붙인다."],
  },
  {
    id: "ID171",
    name: "보이지 않는 준비에 투자한다",
    description: "당장 드러나지 않아도 기반, 공부, 시스템에 자원을 쓴다.",
    opposite: "바로 보이는 결과에 투자한다.",
    relatedAxes: ["Wealth", "Growth"],
    featureSource: ["FEATURE_WEALTH_SYSTEM_ASSET", "FEATURE_GROWTH_ACCUMULATION"],
    confidenceRule: "시스템 자산화와 누적 성장 feature가 함께 있을 때 사용한다.",
    writerHints: ["보이지 않는 기반에 투자한다고 쓴다."],
    readerHints: ["Wealth에 붙인다."],
  },
  {
    id: "ID177",
    name: "일의 흐름을 자산으로 만든다",
    description: "반복되는 업무를 기록과 시스템으로 바꿔 다음 자산으로 남긴다.",
    opposite: "일이 끝나면 흐름도 사라진다.",
    relatedAxes: ["Wealth", "Leadership"],
    featureSource: ["FEATURE_WEALTH_SYSTEM_ASSET", "FEATURE_LEADERSHIP_SYSTEM_THINKING"],
    confidenceRule: "시스템 자산화와 시스템 사고 feature가 함께 있을 때 사용한다.",
    writerHints: ["일의 흐름을 자산으로 만든다고 쓴다."],
    readerHints: ["Wealth와 Leadership에 붙인다."],
  },
  {
    id: "ID185",
    name: "과로를 성과로 착각한다",
    description: "많이 해낸 상태를 좋은 상태로 오해해 쉬는 시점을 놓칠 수 있다.",
    opposite: "과로 신호를 빨리 알아차린다.",
    relatedAxes: ["Health", "Action"],
    featureSource: ["FEATURE_HEALTH_OVERLOAD_DELAY", "FEATURE_ACTION_SUSTAINED_RHYTHM"],
    confidenceRule: "늦게 오는 과부하와 지속 리듬 feature가 함께 있을 때 risk로 사용한다.",
    writerHints: ["성과가 곧 좋은 상태는 아니라고 쓴다."],
    readerHints: ["weakSignals에 붙인다."],
  },
  {
    id: "ID190",
    name: "전환기에 오래 적응한다",
    description: "큰 변화가 오면 바로 새 리듬으로 들어가기보다 적응 시간이 필요하다.",
    opposite: "전환 직후 바로 적응한다.",
    relatedAxes: ["LifeFlow", "Health"],
    featureSource: ["FEATURE_LIFEFLOW_TRANSITION_ADAPTATION", "FEATURE_HEALTH_RHYTHM_RECOVERY"],
    confidenceRule: "전환 적응과 리듬 회복 feature가 함께 있을 때 사용한다.",
    writerHints: ["전환기를 적응 시간으로 쓴다."],
    readerHints: ["LifeFlow에 붙인다."],
  },
  {
    id: "ID195",
    name: "반복 과제가 다시 돌아온다",
    description: "비슷한 선택과 관계 문제가 시간차를 두고 반복될 수 있다.",
    opposite: "매번 전혀 다른 과제를 만난다.",
    relatedAxes: ["LifeFlow", "Conflict"],
    featureSource: ["FEATURE_LIFEFLOW_REPEATING_TASK", "FEATURE_CONFLICT_STRUCTURE_DIAGNOSIS"],
    confidenceRule: "반복 과제와 갈등 구조 진단 feature가 함께 있을 때 사용한다.",
    writerHints: ["예언하지 않고 반복 구조로만 쓴다."],
    readerHints: ["traceSeed에 유용하다."],
  },
  {
    id: "ID196",
    name: "준비한 자원이 때를 만난다",
    description: "오래 쌓아둔 능력이나 관계가 특정 흐름에서 쓰임을 얻는다.",
    opposite: "그때그때 필요한 자원을 만든다.",
    relatedAxes: ["LifeFlow", "Wealth"],
    featureSource: ["FEATURE_LIFEFLOW_PREPARATION_FOR_NEXT", "FEATURE_WEALTH_VALUE_CONVERSION"],
    confidenceRule: "다음 장 준비와 가치 전환 feature가 함께 있을 때 사용한다.",
    writerHints: ["때를 맞힌다는 표현보다 준비한 자원의 쓰임으로 쓴다."],
    readerHints: ["LifeFlow와 Wealth에 붙인다."],
  },
];

export const HUMAN_VOCABULARY: HumanVocabulary[] = HUMAN_VOCABULARY_DRAFTS.map((item) => ({
  ...item,
  category: categoryForId(item.id),
}));

assertVocabularyRegistry(HUMAN_VOCABULARY);
