import type { DecisionDomain } from "./types";

export const DECISION_DOMAINS: DecisionDomain[] = [
  "wealth",
  "career",
  "business",
  "jobChange",
  "businessStart",
  "businessExpansion",
  "partnership",
  "investment",
  "property",
  "contract",
  "relationship",
  "spouse",
  "family",
  "children",
  "parent",
  "health",
  "stress",
  "mobility",
  "travel",
  "overseas",
  "study",
  "reputation",
  "legalRisk",
  "communication",
  "leadership",
];

export type DecisionDomainRule = {
  domain: DecisionDomain;
  blindEvidenceKeys: string[];
  blindPositiveSignalGroups: string[];
  blindRiskSignalGroups: string[];
  futureEvidenceKeys: string[];
  futureTimingSignalGroups: string[];
  timingCodePatterns: RegExp[];
  riskCodePatterns: RegExp[];
};

export const DECISION_DOMAIN_RULES: Record<DecisionDomain, DecisionDomainRule> = {
  wealth: {
    domain: "wealth",
    blindEvidenceKeys: ["wealth"],
    blindPositiveSignalGroups: ["wealthSignals", "cashflowSignals"],
    blindRiskSignalGroups: ["cashflowSignals"],
    futureEvidenceKeys: ["wealthTiming"],
    futureTimingSignalGroups: ["wealthTimingSignals"],
    timingCodePatterns: [/WEALTH/],
    riskCodePatterns: [/PEER_WEALTH|HIGH_RELATION/],
  },
  career: {
    domain: "career",
    blindEvidenceKeys: ["career"],
    blindPositiveSignalGroups: ["careerSignals", "organizationSignals", "authoritySignals"],
    blindRiskSignalGroups: ["stressSignals", "legalRiskSignals"],
    futureEvidenceKeys: ["careerTiming", "contractTiming"],
    futureTimingSignalGroups: ["careerTimingSignals", "contractTimingSignals"],
    timingCodePatterns: [/OFFICER|RESOURCE/],
    riskCodePatterns: [/RELATION|CLASH/],
  },
  business: {
    domain: "business",
    blindEvidenceKeys: ["business", "wealth"],
    blindPositiveSignalGroups: ["businessSignals", "entrepreneurSignals", "salesSignals"],
    blindRiskSignalGroups: ["partnershipSignals", "cashflowSignals"],
    futureEvidenceKeys: ["businessTiming", "wealthTiming"],
    futureTimingSignalGroups: ["businessTimingSignals", "wealthTimingSignals"],
    timingCodePatterns: [/WEALTH|OUTPUT/],
    riskCodePatterns: [/PEER_WEALTH|HIGH_RELATION/],
  },
  jobChange: {
    domain: "jobChange",
    blindEvidenceKeys: ["career", "mobility"],
    blindPositiveSignalGroups: ["careerSignals", "mobilitySignals"],
    blindRiskSignalGroups: ["stressSignals", "legalRiskSignals"],
    futureEvidenceKeys: ["careerTiming", "mobilityTiming"],
    futureTimingSignalGroups: ["careerTimingSignals", "mobilityTimingSignals"],
    timingCodePatterns: [/OFFICER|CLASH|MOVEMENT/],
    riskCodePatterns: [/HIGH_RELATION|CLASH/],
  },
  businessStart: {
    domain: "businessStart",
    blindEvidenceKeys: ["business", "wealth"],
    blindPositiveSignalGroups: ["entrepreneurSignals", "businessSignals", "salesSignals"],
    blindRiskSignalGroups: ["cashflowSignals", "legalRiskSignals"],
    futureEvidenceKeys: ["businessTiming", "wealthTiming", "contractTiming"],
    futureTimingSignalGroups: ["businessTimingSignals", "wealthTimingSignals", "contractTimingSignals"],
    timingCodePatterns: [/WEALTH|OUTPUT|OFFICER/],
    riskCodePatterns: [/HIGH_RELATION|PEER_WEALTH/],
  },
  businessExpansion: {
    domain: "businessExpansion",
    blindEvidenceKeys: ["business", "investment"],
    blindPositiveSignalGroups: ["businessSignals", "entrepreneurSignals", "investmentSignals"],
    blindRiskSignalGroups: ["cashflowSignals", "partnershipSignals"],
    futureEvidenceKeys: ["businessTiming", "investmentTiming"],
    futureTimingSignalGroups: ["businessTimingSignals", "investmentTimingSignals"],
    timingCodePatterns: [/WEALTH|OUTPUT/],
    riskCodePatterns: [/HIGH_RELATION|PEER_WEALTH/],
  },
  partnership: {
    domain: "partnership",
    blindEvidenceKeys: ["relationship", "business"],
    blindPositiveSignalGroups: ["partnershipSignals", "relationshipSignals"],
    blindRiskSignalGroups: ["partnershipSignals", "legalRiskSignals"],
    futureEvidenceKeys: ["relationshipTiming", "contractTiming"],
    futureTimingSignalGroups: ["relationshipTimingSignals", "contractTimingSignals"],
    timingCodePatterns: [/COMBINATION|OFFICER|RESOURCE/],
    riskCodePatterns: [/CLASH|HIGH_RELATION/],
  },
  investment: {
    domain: "investment",
    blindEvidenceKeys: ["investment", "wealth"],
    blindPositiveSignalGroups: ["investmentSignals", "propertySignals", "wealthSignals"],
    blindRiskSignalGroups: ["cashflowSignals"],
    futureEvidenceKeys: ["investmentTiming", "wealthTiming"],
    futureTimingSignalGroups: ["investmentTimingSignals", "wealthTimingSignals"],
    timingCodePatterns: [/WEALTH/],
    riskCodePatterns: [/PEER_WEALTH|HIGH_RELATION/],
  },
  property: {
    domain: "property",
    blindEvidenceKeys: ["investment"],
    blindPositiveSignalGroups: ["propertySignals", "investmentSignals"],
    blindRiskSignalGroups: ["cashflowSignals"],
    futureEvidenceKeys: ["investmentTiming"],
    futureTimingSignalGroups: ["investmentTimingSignals"],
    timingCodePatterns: [/WEALTH/],
    riskCodePatterns: [/HIGH_RELATION/],
  },
  contract: {
    domain: "contract",
    blindEvidenceKeys: ["contract"],
    blindPositiveSignalGroups: ["contractSignals", "studySignals"],
    blindRiskSignalGroups: ["legalRiskSignals"],
    futureEvidenceKeys: ["contractTiming"],
    futureTimingSignalGroups: ["contractTimingSignals"],
    timingCodePatterns: [/OFFICER|RESOURCE/],
    riskCodePatterns: [/CLASH|RELATION/],
  },
  relationship: {
    domain: "relationship",
    blindEvidenceKeys: ["relationship"],
    blindPositiveSignalGroups: ["relationshipSignals", "partnershipSignals"],
    blindRiskSignalGroups: ["relationshipSignals", "spouseSignals"],
    futureEvidenceKeys: ["relationshipTiming"],
    futureTimingSignalGroups: ["relationshipTimingSignals"],
    timingCodePatterns: [/COMBINATION/],
    riskCodePatterns: [/CLASH|PALACE|HIGH_RELATION/],
  },
  spouse: {
    domain: "spouse",
    blindEvidenceKeys: ["relationship"],
    blindPositiveSignalGroups: ["spouseSignals"],
    blindRiskSignalGroups: ["spouseSignals"],
    futureEvidenceKeys: ["relationshipTiming"],
    futureTimingSignalGroups: ["relationshipTimingSignals"],
    timingCodePatterns: [/COMBINATION/],
    riskCodePatterns: [/CLASH|PALACE|HIGH_RELATION/],
  },
  family: {
    domain: "family",
    blindEvidenceKeys: ["relationship"],
    blindPositiveSignalGroups: ["familySignals"],
    blindRiskSignalGroups: ["stressSignals"],
    futureEvidenceKeys: ["relationshipTiming"],
    futureTimingSignalGroups: ["relationshipTimingSignals"],
    timingCodePatterns: [/COMBINATION/],
    riskCodePatterns: [/CLASH|HIGH_RELATION/],
  },
  children: {
    domain: "children",
    blindEvidenceKeys: ["business"],
    blindPositiveSignalGroups: ["childrenSignals"],
    blindRiskSignalGroups: ["stressSignals"],
    futureEvidenceKeys: ["businessTiming"],
    futureTimingSignalGroups: ["businessTimingSignals"],
    timingCodePatterns: [/OUTPUT/],
    riskCodePatterns: [/HIGH_RELATION/],
  },
  parent: {
    domain: "parent",
    blindEvidenceKeys: ["career"],
    blindPositiveSignalGroups: ["parentSignals", "studySignals"],
    blindRiskSignalGroups: ["stressSignals"],
    futureEvidenceKeys: ["contractTiming"],
    futureTimingSignalGroups: ["contractTimingSignals", "studyTimingSignals"],
    timingCodePatterns: [/RESOURCE/],
    riskCodePatterns: [/HIGH_RELATION/],
  },
  health: {
    domain: "health",
    blindEvidenceKeys: ["health"],
    blindPositiveSignalGroups: [],
    blindRiskSignalGroups: ["healthSignals", "stressSignals", "accidentSignals"],
    futureEvidenceKeys: ["healthTiming", "mobilityTiming"],
    futureTimingSignalGroups: ["healthTimingSignals"],
    timingCodePatterns: [/HEALTH|RELATION/],
    riskCodePatterns: [/HEALTH|CLASH|HIGH_RELATION/],
  },
  stress: {
    domain: "stress",
    blindEvidenceKeys: ["health"],
    blindPositiveSignalGroups: [],
    blindRiskSignalGroups: ["stressSignals", "authoritySignals"],
    futureEvidenceKeys: ["healthTiming"],
    futureTimingSignalGroups: ["healthTimingSignals"],
    timingCodePatterns: [/HEALTH|RELATION/],
    riskCodePatterns: [/HEALTH|CLASH|HIGH_RELATION/],
  },
  mobility: {
    domain: "mobility",
    blindEvidenceKeys: ["mobility"],
    blindPositiveSignalGroups: ["mobilitySignals"],
    blindRiskSignalGroups: ["accidentSignals"],
    futureEvidenceKeys: ["mobilityTiming"],
    futureTimingSignalGroups: ["sharedMovementSignals", "mobilityTimingSignals"],
    timingCodePatterns: [/CLASH|MOVEMENT/],
    riskCodePatterns: [/HIGH_RELATION|CLASH/],
  },
  travel: {
    domain: "travel",
    blindEvidenceKeys: ["mobility"],
    blindPositiveSignalGroups: ["travelSignals"],
    blindRiskSignalGroups: ["accidentSignals"],
    futureEvidenceKeys: ["mobilityTiming"],
    futureTimingSignalGroups: ["sharedMovementSignals", "travelTimingSignals"],
    timingCodePatterns: [/CLASH|MOVEMENT/],
    riskCodePatterns: [/HIGH_RELATION|CLASH/],
  },
  overseas: {
    domain: "overseas",
    blindEvidenceKeys: ["mobility"],
    blindPositiveSignalGroups: ["overseasSignals", "travelSignals"],
    blindRiskSignalGroups: ["accidentSignals"],
    futureEvidenceKeys: ["mobilityTiming"],
    futureTimingSignalGroups: ["sharedMovementSignals", "travelTimingSignals"],
    timingCodePatterns: [/CLASH|MOVEMENT/],
    riskCodePatterns: [/HIGH_RELATION|CLASH/],
  },
  study: {
    domain: "study",
    blindEvidenceKeys: ["career"],
    blindPositiveSignalGroups: ["studySignals", "parentSignals"],
    blindRiskSignalGroups: ["stressSignals"],
    futureEvidenceKeys: ["contractTiming"],
    futureTimingSignalGroups: ["studyTimingSignals", "contractTimingSignals"],
    timingCodePatterns: [/RESOURCE/],
    riskCodePatterns: [/HIGH_RELATION/],
  },
  reputation: {
    domain: "reputation",
    blindEvidenceKeys: ["contract"],
    blindPositiveSignalGroups: ["reputationSignals", "communicationSignals"],
    blindRiskSignalGroups: ["legalRiskSignals", "reputationSignals"],
    futureEvidenceKeys: ["relationshipTiming", "contractTiming"],
    futureTimingSignalGroups: ["relationshipTimingSignals", "contractTimingSignals"],
    timingCodePatterns: [/COMBINATION|OFFICER/],
    riskCodePatterns: [/CLASH|HIGH_RELATION/],
  },
  legalRisk: {
    domain: "legalRisk",
    blindEvidenceKeys: ["contract"],
    blindPositiveSignalGroups: ["contractSignals"],
    blindRiskSignalGroups: ["legalRiskSignals"],
    futureEvidenceKeys: ["contractTiming", "mobilityTiming"],
    futureTimingSignalGroups: ["contractTimingSignals", "sharedMovementSignals"],
    timingCodePatterns: [/OFFICER|RESOURCE|CLASH/],
    riskCodePatterns: [/CLASH|RELATION|HIGH_RELATION/],
  },
  communication: {
    domain: "communication",
    blindEvidenceKeys: ["business"],
    blindPositiveSignalGroups: ["communicationSignals", "creativitySignals"],
    blindRiskSignalGroups: ["reputationSignals"],
    futureEvidenceKeys: ["businessTiming"],
    futureTimingSignalGroups: ["businessTimingSignals"],
    timingCodePatterns: [/OUTPUT/],
    riskCodePatterns: [/HIGH_RELATION/],
  },
  leadership: {
    domain: "leadership",
    blindEvidenceKeys: ["career", "business"],
    blindPositiveSignalGroups: ["leadershipSignals", "managementSignals", "organizationSignals"],
    blindRiskSignalGroups: ["authoritySignals", "stressSignals"],
    futureEvidenceKeys: ["careerTiming", "contractTiming"],
    futureTimingSignalGroups: ["careerTimingSignals", "contractTimingSignals"],
    timingCodePatterns: [/OFFICER|RESOURCE/],
    riskCodePatterns: [/HIGH_RELATION/],
  },
};
