import type { BlueprintFeatureDefinition } from "../types/runtime";

export const BLUEPRINT_FEATURES: BlueprintFeatureDefinition[] = [
  {
    id: "FEATURE_IDENTITY_SELF_STANDARD",
    axis: "Identity",
    title: "자기 기준",
    description: "외부 반응보다 스스로 납득되는 기준을 먼저 세우는 구조",
    sourcePaths: ["pillars.day", "elements", "provenance.timeReliability"],
    writerHints: ["고집이 아니라 기준 형성으로 쓴다."],
    readerHints: ["기준이 먼저 보이는 문장에 붙인다."],
    baseConfidence: 0.9,
  },
  {
    id: "FEATURE_IDENTITY_INNER_ALIGNMENT",
    axis: "Identity",
    title: "내부 정렬",
    description: "움직이기 전 안쪽의 이유와 방향을 맞추려는 구조",
    sourcePaths: ["pillars.day", "provenance.timeCorrection.applied"],
    writerHints: ["느림보다 정렬의 시간으로 쓴다."],
    readerHints: ["자기 납득과 연결한다."],
    baseConfidence: 0.86,
  },
  {
    id: "FEATURE_IDENTITY_ROLE_REDEFINITION",
    axis: "Identity",
    title: "역할 재정의",
    description: "주어진 역할을 그대로 받기보다 의미를 다시 잡는 구조",
    sourcePaths: ["pillars.month", "pillars.year"],
    writerHints: ["소속보다 역할의 의미를 먼저 보는 사람으로 쓴다."],
    readerHints: ["역할과 정체 구조에 붙인다."],
    baseConfidence: 0.8,
  },
  {
    id: "FEATURE_IDENTITY_BOUNDARY_FIRST",
    axis: "Identity",
    title: "경계 우선",
    description: "자신이 지킬 선을 확인한 뒤 가까워지거나 맡는 구조",
    sourcePaths: ["pillars.day.ji", "hiddenStems.day"],
    writerHints: ["닫힘이 아니라 유지 가능한 선으로 쓴다."],
    readerHints: ["관계 거리와 함께 보여준다."],
    baseConfidence: 0.82,
  },
  {
    id: "FEATURE_IDENTITY_LONG_TERM_SELF",
    axis: "Identity",
    title: "장기 자기감",
    description: "당장의 반응보다 오래 남는 방향으로 자신을 세우는 구조",
    sourcePaths: ["luck.currentDaeun", "luck.currentYear"],
    writerHints: ["시간이 지나도 남는 기준으로 쓴다."],
    readerHints: ["LifeFlow와 함께 붙인다."],
    baseConfidence: 0.84,
  },
  {
    id: "FEATURE_THINKING_BIG_PICTURE",
    axis: "Thinking",
    title: "큰 그림",
    description: "세부보다 전체 방향과 구조를 먼저 잡는 사고 구조",
    sourcePaths: ["elements", "pillars.month"],
    writerHints: ["대충 봄이 아니라 먼저 지도를 그리는 방식으로 쓴다."],
    readerHints: ["전체 방향 설명에 붙인다."],
    baseConfidence: 0.82,
  },
  {
    id: "FEATURE_THINKING_DETAIL_SENSITIVE",
    axis: "Thinking",
    title: "디테일 감지",
    description: "작은 차이와 예외를 판단 재료로 삼는 구조",
    sourcePaths: ["hiddenStems", "provenance.warnings"],
    writerHints: ["예민함보다 차이를 감지하는 능력으로 쓴다."],
    readerHints: ["검증 문장에 붙인다."],
    baseConfidence: 0.78,
  },
  {
    id: "FEATURE_THINKING_PATTERN_SEEKING",
    axis: "Thinking",
    title: "패턴 탐색",
    description: "반복되는 흐름과 조건을 찾아내는 사고 구조",
    sourcePaths: ["tenGods", "twelveStages"],
    writerHints: ["사건보다 반복 구조를 읽는 사람으로 쓴다."],
    readerHints: ["반복과 흐름 문장에 붙인다."],
    baseConfidence: 0.88,
  },
  {
    id: "FEATURE_THINKING_CONTEXT_READING",
    axis: "Thinking",
    title: "맥락 읽기",
    description: "드러난 말보다 그 말이 놓인 조건을 함께 보는 구조",
    sourcePaths: ["pillars.month", "pillars.day"],
    writerHints: ["눈치가 아니라 맥락 독해로 쓴다."],
    readerHints: ["관계와 소통 문장에 붙인다."],
    baseConfidence: 0.84,
  },
  {
    id: "FEATURE_THINKING_QUESTION_DRIVEN",
    axis: "Thinking",
    title: "질문 기반 사고",
    description: "답을 먼저 닫기보다 질문을 바꾸며 생각하는 구조",
    sourcePaths: ["pillars.day", "tenGods"],
    writerHints: ["망설임보다 질문의 이동으로 쓴다."],
    readerHints: ["사고 챕터의 전환에 붙인다."],
    baseConfidence: 0.8,
  },
  {
    id: "FEATURE_THINKING_LAYERED_MEMORY",
    axis: "Thinking",
    title: "층으로 쌓는 기억",
    description: "정보를 단번에 소비하지 않고 층으로 쌓아 연결하는 구조",
    sourcePaths: ["hiddenStems", "twelveStages"],
    writerHints: ["생각이 많다가 아니라 근거가 층을 이룬다고 쓴다."],
    readerHints: ["검토와 축적 문장에 붙인다."],
    baseConfidence: 0.86,
  },
  {
    id: "FEATURE_THINKING_STRUCTURE_FIRST",
    axis: "Thinking",
    title: "구조 우선",
    description: "개별 사건보다 그것을 가능하게 한 구조를 먼저 보는 방식",
    sourcePaths: ["elements", "luck.currentDaeun"],
    writerHints: ["문제를 다시 정의하는 힘으로 쓴다."],
    readerHints: ["구조 해석 문장에 붙인다."],
    baseConfidence: 0.87,
  },
  {
    id: "FEATURE_THINKING_EVIDENCE_CHECK",
    axis: "Thinking",
    title: "근거 확인",
    description: "느낌이나 의견을 실제 근거와 맞춰보는 구조",
    sourcePaths: ["provenance", "provenance.warnings", "provenance.timeCorrection"],
    writerHints: ["불신보다 확인의 습관으로 쓴다."],
    readerHints: ["confidence가 높은 문장에 붙인다."],
    baseConfidence: 0.83,
  },
  {
    id: "FEATURE_DECISION_CRITERIA",
    axis: "Decision",
    title: "결정 기준",
    description: "선택 전에 판단 기준을 먼저 만드는 구조",
    sourcePaths: ["pillars.day", "pillars.month", "luck.currentDaeun"],
    writerHints: ["결정이 느린 사람이 아니라 기준을 만드는 사람으로 쓴다."],
    readerHints: ["ID001과 강하게 연결한다."],
    baseConfidence: 0.94,
  },
  {
    id: "FEATURE_DECISION_VERIFICATION",
    axis: "Decision",
    title: "검증 후 이동",
    description: "가능성이 보인 뒤에도 검증을 거쳐 움직이는 구조",
    sourcePaths: ["tenGods", "provenance.solarTermEngine", "provenance.calendarConversionVerified"],
    writerHints: ["회피가 아니라 검증 후 실행으로 쓴다."],
    readerHints: ["Annotated Mode의 보조 구조로 좋다."],
    baseConfidence: 0.9,
  },
  {
    id: "FEATURE_DECISION_RESPONSIBILITY_RANGE",
    axis: "Decision",
    title: "책임 범위 계산",
    description: "선택 이후 감당해야 할 범위를 먼저 보는 구조",
    sourcePaths: ["pillars.month", "pillars.day", "luck.currentDaeun"],
    writerHints: ["망설임을 책임 계산으로 번역한다."],
    readerHints: ["책임과 결정 문장에 붙인다."],
    baseConfidence: 0.88,
  },
  {
    id: "FEATURE_DECISION_LONG_TERM_VIEW",
    axis: "Decision",
    title: "장기 관점",
    description: "당장의 편함보다 시간이 지나도 유지될 선택을 보는 구조",
    sourcePaths: ["luck.currentDaeun", "luck.currentYear", "twelveStages"],
    writerHints: ["오래 남는 방향이라는 표현을 쓴다."],
    readerHints: ["LifeFlow와 함께 보여준다."],
    baseConfidence: 0.86,
  },
  {
    id: "FEATURE_DECISION_REVERSIBLE_PATH",
    axis: "Decision",
    title: "수정 가능한 경로",
    description: "되돌릴 수 없는 결정보다 조정 가능한 길을 선호하는 구조",
    sourcePaths: ["provenance.warnings", "luck.currentMonth"],
    writerHints: ["신중함보다 개정 가능성을 남기는 방식으로 쓴다."],
    readerHints: ["Tension 설명에 붙인다."],
    baseConfidence: 0.72,
  },
  {
    id: "FEATURE_DECISION_RESOURCE_CHECK",
    axis: "Decision",
    title: "자원 점검",
    description: "시간, 체력, 관계, 돈의 비용을 함께 계산하는 구조",
    sourcePaths: ["elements", "luck.currentDaeun"],
    writerHints: ["감당 가능한 범위를 먼저 본다고 쓴다."],
    readerHints: ["Wealth와 연결한다."],
    baseConfidence: 0.82,
  },
  {
    id: "FEATURE_DECISION_CONDITION_TRIGGERED_SPEED",
    axis: "Decision",
    title: "조건 충족 후 속도",
    description: "조건이 맞을 때 결정과 실행 속도가 빨라지는 구조",
    sourcePaths: ["pillars.hour", "luck.currentDay"],
    writerHints: ["항상 느린 사람이 아니라 조건형 속도로 쓴다."],
    readerHints: ["반대 신호 보정에 붙인다."],
    baseConfidence: 0.78,
  },
  {
    id: "FEATURE_ACTION_EXECUTION_DRIVEN",
    axis: "Action",
    title: "실행 증명",
    description: "말보다 실제 움직임으로 생각을 확인하는 구조",
    sourcePaths: ["pillars.hour", "luck.currentDay"],
    writerHints: ["행동으로 증명한다는 문장에 쓴다."],
    readerHints: ["실행 문장에 붙인다."],
    baseConfidence: 0.76,
  },
  {
    id: "FEATURE_ACTION_SLOW_IGNITION",
    axis: "Action",
    title: "늦게 붙는 실행",
    description: "시작은 조심스럽지만 리듬이 잡히면 오래 가는 구조",
    sourcePaths: ["twelveStages", "luck.currentDaeun"],
    writerHints: ["불꽃보다 불씨에 가까운 리듬으로 쓴다."],
    readerHints: ["Action 핵심 Annotation에 붙인다."],
    baseConfidence: 0.84,
  },
  {
    id: "FEATURE_ACTION_SUSTAINED_RHYTHM",
    axis: "Action",
    title: "지속 리듬",
    description: "한 번 잡은 흐름을 오래 유지하는 구조",
    sourcePaths: ["twelveStages", "luck.currentDaeun"],
    writerHints: ["지속력을 반복 신뢰로 쓴다."],
    readerHints: ["성장과 함께 보여준다."],
    baseConfidence: 0.82,
  },
  {
    id: "FEATURE_ACTION_ROUTINE_POWER",
    axis: "Action",
    title: "루틴 힘",
    description: "반복 가능한 순서와 리듬 안에서 실행이 안정되는 구조",
    sourcePaths: ["provenance.timeCorrection", "pillars.hour"],
    writerHints: ["규칙에 갇힘이 아니라 힘이 나는 순서로 쓴다."],
    readerHints: ["Health와 연결한다."],
    baseConfidence: 0.74,
  },
  {
    id: "FEATURE_ACTION_DEADLINE_ACTIVATION",
    axis: "Action",
    title: "마감 활성",
    description: "시간 제한이 분명할 때 우선순위와 실행이 살아나는 구조",
    sourcePaths: ["luck.currentDay", "luck.currentHour"],
    writerHints: ["압박 아래 선명해지는 움직임으로 쓴다."],
    readerHints: ["조건형 실행 문장에 붙인다."],
    baseConfidence: 0.7,
  },
  {
    id: "FEATURE_ACTION_ADAPTIVE_EXECUTION",
    axis: "Action",
    title: "현장 조정",
    description: "계획대로만 가지 않고 실행 중 얻은 정보를 반영하는 구조",
    sourcePaths: ["provenance.warnings", "luck.currentMonth"],
    writerHints: ["방식부터 바꾸는 사람으로 쓴다."],
    readerHints: ["Growth와 연결한다."],
    baseConfidence: 0.76,
  },
  {
    id: "FEATURE_ACTION_COMPLETION_STACKING",
    axis: "Action",
    title: "작은 완료 누적",
    description: "작은 완료를 쌓아 추진력을 만드는 구조",
    sourcePaths: ["elements", "luck.currentDay"],
    writerHints: ["작은 완료가 다음 실행을 만든다고 쓴다."],
    readerHints: ["실행과 자원 문장에 붙인다."],
    baseConfidence: 0.75,
  },
  {
    id: "FEATURE_RELATIONSHIP_TRUST_BEFORE_SPEED",
    axis: "Relationship",
    title: "속도보다 신뢰",
    description: "빠른 친밀감보다 오래 남을 신뢰 조건을 먼저 보는 구조",
    sourcePaths: ["pillars.day.ji", "pillars.month.ji"],
    writerHints: ["마음을 주지 않는 사람이 아니라 마음을 둘 자리를 확인한다고 쓴다."],
    readerHints: ["관계 핵심 구조로 붙인다."],
    baseConfidence: 0.9,
  },
  {
    id: "FEATURE_RELATIONSHIP_DISTANCE_CONTROL",
    axis: "Relationship",
    title: "거리 조절",
    description: "가까운 관계에서도 자신이 유지될 거리를 확보하는 구조",
    sourcePaths: ["pillars.day", "hiddenStems.day"],
    writerHints: ["차가움보다 관계를 오래 지키는 거리로 쓴다."],
    readerHints: ["Health와 함께 붙인다."],
    baseConfidence: 0.84,
  },
  {
    id: "FEATURE_RELATIONSHIP_OBSERVATION",
    axis: "Relationship",
    title: "관계 관찰",
    description: "가까워지기 전 말과 행동의 반복을 오래 보는 구조",
    sourcePaths: ["tenGods", "hiddenStems"],
    writerHints: ["사람을 오래 관찰한다고 쓴다."],
    readerHints: ["Thinking과 연결한다."],
    baseConfidence: 0.83,
  },
  {
    id: "FEATURE_RELATIONSHIP_RESPONSIBILITY",
    axis: "Relationship",
    title: "관계 책임",
    description: "가까운 사람에게 자신의 몫을 분명히 가져가는 구조",
    sourcePaths: ["pillars.month", "pillars.day"],
    writerHints: ["큰 표현보다 반복되는 책임으로 마음을 보인다고 쓴다."],
    readerHints: ["관계 유지 문장에 붙인다."],
    baseConfidence: 0.82,
  },
  {
    id: "FEATURE_RELATIONSHIP_CONNECTION_BUILDING",
    axis: "Relationship",
    title: "연결 만들기",
    description: "사람, 정보, 역할 사이의 연결점을 찾는 구조",
    sourcePaths: ["pillars.year", "luck.currentYear"],
    writerHints: ["관계를 넓히는 것이 아니라 연결점을 만든다고 쓴다."],
    readerHints: ["확장 흐름과 함께 붙인다."],
    baseConfidence: 0.72,
  },
  {
    id: "FEATURE_RELATIONSHIP_LONG_TERM_MAINTENANCE",
    axis: "Relationship",
    title: "장기 유지",
    description: "시작보다 오래 유지하고 챙기는 데 힘이 있는 구조",
    sourcePaths: ["luck.currentDaeun", "twelveStages"],
    writerHints: ["오래 닫히지 않는 방 같은 관계로 쓴다."],
    readerHints: ["장기 관계 문장에 붙인다."],
    baseConfidence: 0.84,
  },
  {
    id: "FEATURE_COMMUNICATION_WRITTEN_CLARITY",
    axis: "Communication",
    title: "글의 선명함",
    description: "말보다 글이나 정리된 문장에서 기준이 선명해지는 구조",
    sourcePaths: ["pillars.day", "hiddenStems"],
    writerHints: ["말이 늦어도 정리된 문장은 선명하다고 쓴다."],
    readerHints: ["저자 노트와 연결한다."],
    baseConfidence: 0.78,
  },
  {
    id: "FEATURE_COMMUNICATION_LATE_CLEAR_VOICE",
    axis: "Communication",
    title: "늦지만 분명한 말",
    description: "즉각 표현보다 정리된 뒤의 말에 힘이 생기는 구조",
    sourcePaths: ["pillars.hour", "pillars.day"],
    writerHints: ["침묵을 결핍이 아니라 말의 책임으로 쓴다."],
    readerHints: ["소통 핵심 구조에 붙인다."],
    baseConfidence: 0.84,
  },
  {
    id: "FEATURE_COMMUNICATION_CONTEXT_EXPLANATION",
    axis: "Communication",
    title: "맥락 설명",
    description: "결론만 말하기보다 배경과 조건을 함께 전하는 구조",
    sourcePaths: ["pillars.month", "elements"],
    writerHints: ["길게 말함보다 오해를 줄이는 설명으로 쓴다."],
    readerHints: ["Thinking과 연결한다."],
    baseConfidence: 0.8,
  },
  {
    id: "FEATURE_COMMUNICATION_ACTION_CHANNEL",
    axis: "Communication",
    title: "행동 채널",
    description: "마음이나 기준을 말보다 행동으로 전달하는 구조",
    sourcePaths: ["pillars.hour", "luck.currentDay"],
    writerHints: ["챙김과 행동으로 마음을 보인다고 쓴다."],
    readerHints: ["Relationship과 함께 붙인다."],
    baseConfidence: 0.76,
  },
  {
    id: "FEATURE_COMMUNICATION_QUESTION_PERSUASION",
    axis: "Communication",
    title: "질문 설득",
    description: "주장보다 질문으로 상대가 스스로 보게 하는 구조",
    sourcePaths: ["tenGods", "pillars.month"],
    writerHints: ["질문으로 생각을 열어준다고 쓴다."],
    readerHints: ["Leadership과 연결한다."],
    baseConfidence: 0.72,
  },
  {
    id: "FEATURE_COMMUNICATION_WORD_RESPONSIBILITY",
    axis: "Communication",
    title: "말의 책임",
    description: "한 번 꺼낸 말이 관계와 선택에 남는다고 보는 구조",
    sourcePaths: ["pillars.day", "provenance.timeReliability"],
    writerHints: ["말이 적은 이유를 책임의 무게로 쓴다."],
    readerHints: ["침묵 설명에 붙인다."],
    baseConfidence: 0.86,
  },
  {
    id: "FEATURE_LEADERSHIP_STANDARD_BASED",
    axis: "Leadership",
    title: "기준 기반 영향",
    description: "감정 호소보다 기준을 세워 주변을 정렬시키는 구조",
    sourcePaths: ["pillars.month", "pillars.year"],
    writerHints: ["화려한 장악보다 기준점으로 쓴다."],
    readerHints: ["Leadership 핵심 구조에 붙인다."],
    baseConfidence: 0.84,
  },
  {
    id: "FEATURE_LEADERSHIP_SYSTEM_THINKING",
    axis: "Leadership",
    title: "시스템 사고",
    description: "특정 사람보다 일이 반복 가능하게 돌아가는 구조를 보는 방식",
    sourcePaths: ["elements", "pillars.month"],
    writerHints: ["사람보다 시스템을 본다고 쓴다."],
    readerHints: ["Structure First와 연결한다."],
    baseConfidence: 0.83,
  },
  {
    id: "FEATURE_LEADERSHIP_QUIET_INFLUENCE",
    axis: "Leadership",
    title: "조용한 영향력",
    description: "앞에서 외치기보다 반복된 신뢰로 영향력을 만드는 구조",
    sourcePaths: ["luck.currentDaeun", "twelveStages"],
    writerHints: ["조용하지만 오래 확인되는 사람으로 쓴다."],
    readerHints: ["Reader에서는 과장하지 않는다."],
    baseConfidence: 0.8,
  },
  {
    id: "FEATURE_LEADERSHIP_CRISIS_ROLE",
    axis: "Leadership",
    title: "위기 역할",
    description: "문제가 생겼을 때 우선순위와 역할이 선명해지는 구조",
    sourcePaths: ["luck.currentYear", "luck.currentDay"],
    writerHints: ["위기에서 기준을 세우는 방식으로 쓴다."],
    readerHints: ["Conflict와 함께 붙인다."],
    baseConfidence: 0.7,
  },
  {
    id: "FEATURE_LEADERSHIP_DELEGATION_STRUCTURE",
    axis: "Leadership",
    title: "역할 배치",
    description: "각자가 맡을 수 있는 몫을 나눠 일이 굴러가게 하는 구조",
    sourcePaths: ["pillars.year", "luck.currentYear"],
    writerHints: ["혼자 처리보다 역할 배치로 쓴다."],
    readerHints: ["Wealth 자원 배분과 연결한다."],
    baseConfidence: 0.68,
  },
  {
    id: "FEATURE_CONFLICT_BOUNDARY_AFTER_PATIENCE",
    axis: "Conflict",
    title: "참은 뒤의 경계",
    description: "갈등을 바로 터뜨리기보다 기준이 무너졌을 때 선을 긋는 구조",
    sourcePaths: ["pillars.day.ji", "pillars.month.ji"],
    writerHints: ["분노가 아니라 오래 참은 기준의 회복으로 쓴다."],
    readerHints: ["관계 갈등 Annotation에 붙인다."],
    baseConfidence: 0.86,
  },
  {
    id: "FEATURE_CONFLICT_STRUCTURE_DIAGNOSIS",
    axis: "Conflict",
    title: "갈등 구조 진단",
    description: "개인 감정보다 반복되는 조건과 구조를 먼저 보는 방식",
    sourcePaths: ["tenGods", "elements"],
    writerHints: ["감정 크기보다 반복 구조를 본다고 쓴다."],
    readerHints: ["Thinking과 연결한다."],
    baseConfidence: 0.82,
  },
  {
    id: "FEATURE_CONFLICT_PREVENTIVE_RULES",
    axis: "Conflict",
    title: "예방 기준",
    description: "문제가 커지기 전 기준과 기대를 맞춰 갈등을 줄이는 구조",
    sourcePaths: ["pillars.month", "provenance.warnings"],
    writerHints: ["미리 기준을 맞추는 사람으로 쓴다."],
    readerHints: ["Decision과 함께 붙인다."],
    baseConfidence: 0.74,
  },
  {
    id: "FEATURE_CONFLICT_DIRECT_CHECK",
    axis: "Conflict",
    title: "직접 확인",
    description: "애매한 긴장보다 직접 확인하는 편을 택하는 구조",
    sourcePaths: ["pillars.hour", "luck.currentDay"],
    writerHints: ["상황에 따라 직접 확인하는 힘으로 쓴다."],
    readerHints: ["Communication과 연결한다."],
    baseConfidence: 0.7,
  },
  {
    id: "FEATURE_CONFLICT_REPAIR_CONDITIONS",
    axis: "Conflict",
    title: "회복 조건",
    description: "시간만으로 풀기보다 바뀐 조건을 확인해야 회복되는 구조",
    sourcePaths: ["pillars.day", "luck.currentMonth"],
    writerHints: ["화해에도 조건이 필요하다고 쓴다."],
    readerHints: ["관계 회복 문장에 붙인다."],
    baseConfidence: 0.76,
  },
  {
    id: "FEATURE_GROWTH_ACCUMULATION",
    axis: "Growth",
    title: "누적 성장",
    description: "한 번에 바뀌기보다 오래 쌓이며 달라지는 구조",
    sourcePaths: ["luck.currentDaeun", "twelveStages"],
    writerHints: ["폭발적 변화보다 축적의 변화로 쓴다."],
    readerHints: ["성장 핵심 구조에 붙인다."],
    baseConfidence: 0.88,
  },
  {
    id: "FEATURE_GROWTH_SELF_REVISION",
    axis: "Growth",
    title: "자기 수정",
    description: "경험이 쌓이면 기존 기준을 다시 다듬는 구조",
    sourcePaths: ["provenance.warnings", "luck.currentDaeun"],
    writerHints: ["고정된 사람이 아니라 기준을 갱신하는 사람으로 쓴다."],
    readerHints: ["개정판과 연결한다."],
    baseConfidence: 0.82,
  },
  {
    id: "FEATURE_GROWTH_FAILURE_TO_RULE",
    axis: "Growth",
    title: "실패를 기준으로 전환",
    description: "실패를 지나간 사건이 아니라 다음 기준으로 저장하는 구조",
    sourcePaths: ["tenGods", "provenance.warnings"],
    writerHints: ["실패의 이유를 지나치지 않는다고 쓴다."],
    readerHints: ["Conflict와 함께 붙인다."],
    baseConfidence: 0.78,
  },
  {
    id: "FEATURE_GROWTH_CHANGE_TRIGGER",
    axis: "Growth",
    title: "변화 성장",
    description: "익숙한 구조가 흔들릴 때 새로운 능력이 열리는 구조",
    sourcePaths: ["luck.currentYear", "luck.currentDaeun"],
    writerHints: ["변화가 올 때 새 능력이 열린다고 쓰되 예언하지 않는다."],
    readerHints: ["LifeFlow와 연결한다."],
    baseConfidence: 0.72,
  },
  {
    id: "FEATURE_WEALTH_RESOURCE_ORDER",
    axis: "Wealth",
    title: "자원의 질서",
    description: "돈보다 자원을 다루는 기준과 지속 가능성을 보는 구조",
    sourcePaths: ["elements", "luck.currentDaeun"],
    writerHints: ["돈복이 아니라 자원을 대하는 질서로 쓴다."],
    readerHints: ["Wealth 핵심 구조에 붙인다."],
    baseConfidence: 0.82,
  },
  {
    id: "FEATURE_WEALTH_VALUE_CONVERSION",
    axis: "Wealth",
    title: "가치 전환",
    description: "능력과 경험을 실제 쓸 수 있는 자원으로 바꾸는 구조",
    sourcePaths: ["pillars.hour", "luck.currentYear"],
    writerHints: ["가치를 자원으로 바꾼다고 쓴다."],
    readerHints: ["Action과 함께 붙인다."],
    baseConfidence: 0.76,
  },
  {
    id: "FEATURE_WEALTH_STABILITY_BEFORE_EXPANSION",
    axis: "Wealth",
    title: "안정 후 확장",
    description: "기본 자원이 확보되어야 더 큰 시도를 시작하는 구조",
    sourcePaths: ["luck.currentDaeun", "elements"],
    writerHints: ["확장보다 감당 가능한 기반으로 쓴다."],
    readerHints: ["Decision과 연결한다."],
    baseConfidence: 0.84,
  },
  {
    id: "FEATURE_WEALTH_TIME_COST_AWARENESS",
    axis: "Wealth",
    title: "시간 비용 감각",
    description: "돈뿐 아니라 시간과 집중력 손실을 비용으로 계산하는 구조",
    sourcePaths: ["provenance.timeCorrection", "luck.currentMonth"],
    writerHints: ["비용을 시간과 집중력까지 넓혀 쓴다."],
    readerHints: ["Health와 함께 붙인다."],
    baseConfidence: 0.74,
  },
  {
    id: "FEATURE_WEALTH_SYSTEM_ASSET",
    axis: "Wealth",
    title: "시스템 자산화",
    description: "반복되는 일의 흐름을 기록과 시스템으로 남기는 구조",
    sourcePaths: ["pillars.month", "elements"],
    writerHints: ["일의 흐름을 자산으로 만든다고 쓴다."],
    readerHints: ["Leadership과 함께 붙인다."],
    baseConfidence: 0.78,
  },
  {
    id: "FEATURE_HEALTH_RHYTHM_RECOVERY",
    axis: "Health",
    title: "리듬 회복",
    description: "무리한 버팀보다 자기 리듬 회복이 중요한 구조",
    sourcePaths: ["provenance.timeCorrection", "pillars.hour", "provenance.warnings"],
    writerHints: ["진단하지 않고 회복 리듬의 중요성으로 쓴다."],
    readerHints: ["Health 핵심 구조에 붙인다."],
    baseConfidence: 0.82,
  },
  {
    id: "FEATURE_HEALTH_QUIET_RECOVERY",
    axis: "Health",
    title: "조용한 회복",
    description: "외부 입력을 줄이고 혼자 정리할 때 회복되는 구조",
    sourcePaths: ["pillars.day", "hiddenStems"],
    writerHints: ["혼자 있는 시간이 관계를 지킨다고 쓴다."],
    readerHints: ["Relationship과 함께 붙인다."],
    baseConfidence: 0.8,
  },
  {
    id: "FEATURE_HEALTH_OVERLOAD_DELAY",
    axis: "Health",
    title: "늦게 오는 과부하",
    description: "당장은 버티지만 시간이 지난 뒤 소모가 올라오는 구조",
    sourcePaths: ["provenance.warnings", "twelveStages"],
    writerHints: ["버틸 수 있음과 쉬어야 함을 함께 쓴다."],
    readerHints: ["Risk 이유에 붙인다."],
    baseConfidence: 0.76,
  },
  {
    id: "FEATURE_HEALTH_SLEEP_DECISION_LINK",
    axis: "Health",
    title: "리듬과 판단 연결",
    description: "수면과 생활 리듬이 흔들릴 때 판단도 함께 흐려지는 구조",
    sourcePaths: ["provenance.timeCorrection", "provenance.unknownTime"],
    writerHints: ["의학 진단 없이 리듬 민감도로 쓴다."],
    readerHints: ["Decision risk와 연결한다."],
    baseConfidence: 0.7,
  },
  {
    id: "FEATURE_HEALTH_STOP_AS_RECOVERY",
    axis: "Health",
    title: "멈춤 회복",
    description: "멈춤을 실패가 아니라 다음 실행을 위한 조정으로 쓰는 구조",
    sourcePaths: ["luck.currentDaeun", "provenance.warnings"],
    writerHints: ["멈춤을 실행의 일부로 쓴다."],
    readerHints: ["Action과 함께 붙인다."],
    baseConfidence: 0.78,
  },
  {
    id: "FEATURE_LIFEFLOW_REALIGNMENT",
    axis: "LifeFlow",
    title: "재정렬 흐름",
    description: "새 결론보다 방향과 기준을 다시 세우는 흐름",
    sourcePaths: ["luck.currentDaeun", "luck.currentYear"],
    writerHints: ["미래 예언이 아니라 다음 장 전의 정리로 쓴다."],
    readerHints: ["LifeFlow 핵심 구조에 붙인다."],
    baseConfidence: 0.86,
  },
  {
    id: "FEATURE_LIFEFLOW_TRANSITION_ADAPTATION",
    axis: "LifeFlow",
    title: "전환 적응",
    description: "큰 변화 뒤 새 리듬에 들어가기까지 적응 시간이 필요한 구조",
    sourcePaths: ["luck.currentDaeun.startDateTime", "luck.currentDaeun.endDateTime"],
    writerHints: ["전환기를 단정하지 않고 적응의 시간으로 쓴다."],
    readerHints: ["현재 위치 문장에 붙인다."],
    baseConfidence: 0.78,
  },
  {
    id: "FEATURE_LIFEFLOW_PREPARATION_FOR_NEXT",
    axis: "LifeFlow",
    title: "다음 장 준비",
    description: "현재 결론보다 다음 시기에 필요한 자원과 태도를 준비하는 구조",
    sourcePaths: ["luck.currentDaeun", "luck.currentYear"],
    writerHints: ["다음 장을 준비한다고 쓴다."],
    readerHints: ["마지막 챕터에 붙인다."],
    baseConfidence: 0.84,
  },
  {
    id: "FEATURE_LIFEFLOW_REPEATING_TASK",
    axis: "LifeFlow",
    title: "반복 과제",
    description: "비슷한 선택과 관계 문제가 시간차를 두고 반복되는 구조",
    sourcePaths: ["tenGods", "luck.currentDaeun", "luck.currentYear"],
    writerHints: ["반복되는 구조는 읽을 수 있다고 쓴다."],
    readerHints: ["Growth와 Conflict에 연결한다."],
    baseConfidence: 0.82,
  },
  {
    id: "FEATURE_LIFEFLOW_TIMING_MODIFIER",
    axis: "LifeFlow",
    title: "흐름 보정",
    description: "같은 구조라도 현재 흐름에 따라 강도가 달라지는 구조",
    sourcePaths: ["luck", "luck.currentDaeun", "luck.currentMonth"],
    writerHints: ["현재 흐름에서 커지는 구조로만 표현하고 예언하지 않는다."],
    readerHints: ["Confidence 보정에 붙인다."],
    baseConfidence: 0.8,
  },
];
